debug: false

codegen:
  db: oracle
  driver: oracle.jdbc.driver.OracleDriver
  url: jdbc:oracle:thin:@117.25.174.10:1521:orcl
  username: klxx_rls
  password: klxx_rls
  author: zenglw
  tablePrefix: TAB_
  tableSuffix:
  templatePath: classpath:templates/genCode/base
  projectPath: D:\IdeaProjects\ta\ta-base\base-core
  javaPath: src/main/java
  resourcesPath: src/main/resources
  javaFiles:
    -
      templateName: mapper.template
      packageName: com.klxx.ta.base.mapper
      fileSuffix: Mapper
    -
      templateName: repository.template
      packageName: com.klxx.ta.base.repository
      fileSuffix: Repository
    -
      templateName: service.template
      packageName: com.klxx.ta.base.service
      fileSuffix: service
    -
      templateName: model.template
      packageName: com.klxx.ta.base.domain
      filePath: D:\IdeaProjects\ta\ta-base\base-facade\src\main\java

#  resourcesFiles:

  generateTable:
    - TAB_DATA_DEVICE
    - TAB_DATA_GRADE
