debug: false

codegen:
  db: oracle
  driver: oracle.jdbc.driver.OracleDriver
  url: 数据库url
  username: 数据库用户名
  password: 数据库密码
  author: zenglw
  tablePrefix: T_
  tableSuffix:
  templatePath: classpath:templates/genCode/base
  projectPath: D:\IdeaProjects\ta\ta-goods\goods-course\course-core
  javaPath: src/main/java
  resourcesPath: src/main/resources
  javaFiles:
    -
      templateName: mapper.template
      packageName: com.klxx.ta.course.mapper
      fileSuffix: Mapper
    -
      templateName: repository.template
      packageName: com.klxx.ta.course.repository
      fileSuffix: repository
    -
      templateName: service.template
      packageName: com.klxx.ta.course.service
      fileSuffix: service
    -
      templateName: model.template
      packageName: com.klxx.ta.course.domain
      filePath:  D:\IdeaProjects\ta\ta-goods\goods-course\course-facade\src\main\java

#  resourcesFiles:

  generateTable:
    - T_COURSE
    - T_COURSE_SCHEDULING
