debug: true

codegen:
  db: oracle
  driver: oracle.jdbc.driver.OracleDriver
  url: 数据库url
  username: 数据库用户名
  password: 数据库密码
  author: zenglw
  tablePrefix: T_
  tableSuffix:
  templatePath: classpath:templates/genCode/base
  projectPath: E:/IdeaProjects/code-gen
  javaPath: src/main/java
  resourcesPath: src/main/resources
  javaFiles:
    -
      templateName: repository.template
      packageName: com.codegen.demo.repository
      fileSuffix: repository
    -
      templateName: service.template
      packageName: com.codegen.demo.service
      fileSuffix: service
    -
      templateName: model.template
      packageName: com.codegen.demo.model
      filePath: E:\IdeaProjects\code-gen\src\main\java

#  resourcesFiles:

  generateTable:
    - T_ACCOUNT
