debug: false

codegen:
  db: oracle
  driver: oracle.jdbc.driver.OracleDriver
  url: 数据库url
  username: 数据库用户名
  password: 数据库密码
  author: zenglw
  tablePrefix: Tab_
  tableSuffix:
  templatePath: classpath:templates/genCode/base
  projectPath: E:\IdeaProjects\erp\erp_foundation\erp_foundation_core
  javaPath: src/main/java
  resourcesPath: src/main/resources
  javaFiles:
    -
      templateName: mapper.template
      packageName: com.klxx.erp.foundation.mapper
      fileSuffix: mapper
    -
      templateName: repository.template
      packageName: com.klxx.erp.foundation.repository
      fileSuffix: repository
    -
      templateName: service.template
      packageName: com.klxx.erp.foundation.service
      fileSuffix: service
    -
      templateName: model.template
      packageName: com.klxx.erp.foundation.domain
      filePath: E:\IdeaProjects\erp\erp_foundation\erp_foundation_facade\src\main\java

#  resourcesFiles:

  generateTable:
    - tab_organization_info
